---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: ci
      include: scope
    assignees:
      - ViBiOh
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    assignees:
      - ViBiOh
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: chore
      include: scope
    assignees:
      - ViBiOh
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
