---
version: 2

updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
      time: "06:00"
      day: friday
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      time: "06:00"
      day: friday
    commit-message:
      prefix: chore
      include: scope
