language: java
sudo: required
jdk:
- openjdk8
services:
- docker
script: |
  mvn clean install docker:build
after_success: |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker login -u=${DOCKER_USER} -p=${DOCKER_PASS} && docker push ${DOCKER_USER}/spring-web-bp
  fi
notifications:
  email: false
deploy:
  provider: script
  skip_cleanup: true
  script: "curl -H 'Authorization: GitHub ${GITHUB_OAUTH_TOKEN}' -X POST https://dashboard-api.vibioh.fr/containers/spring/ --data-binary @docker-compose.yml"
  on:
    branch: master
