language: java
sudo: required
jdk:
- oraclejdk8
services:
- docker
script:
- docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
- mvn clean install docker:build
- docker push vibioh/spring-web-bp
notifications:
  email: false
