language: java
sudo: required
jdk:
- openjdk8
services:
- docker
script: |
  mvn clean install docker:build
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_afb3f4a0fd37_key -iv $encrypted_afb3f4a0fd37_iv -in deploy_rsa.enc -out deploy_rsa -d
before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: |
    true &&
    docker login -u=${DOCKER_USER} -p=${DOCKER_PASS} &&
    docker push ${DOCKER_USER}/spring-web-bp &&
    ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "bash -s" 2>/dev/null -- < ./deploy.sh spring https://github.com/ViBiOh/spring-web-bp.git vibioh.fr
  on:
    branch: master
