language: java
sudo: required
jdk:
  - oraclejdk8
services:
  - docker
script: |
  docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  mvn clean install docker:build -DpushImage
notifications:
  email: false
