language: java
sudo: required
jdk:
- oraclejdk8
services:
- docker
script:
- docker login -u=${DOCKER_USER} -p=${DOCKER_PASS}
- mvn clean install docker:build
- docker push ${DOCKER_USER}/spring-web-bp
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_afb3f4a0fd37_key -iv $encrypted_afb3f4a0fd37_iv
  -in deploy_rsa.enc -out deploy_rsa -d
