version: '2'

services:
  spring:
    image: vibioh/spring-web-bp
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: spring.l3miage.fr'
      traefik.port: '8080'
      traefik.frontend.rateLimit.extractorFunc: 'client.ip'
      traefik.frontend.rateLimit.rateSet.first.period: '60s'
      traefik.frontend.rateLimit.rateSet.first.average: '100'
      traefik.frontend.rateLimit.rateSet.first.burst: '200'
    logging:
      driver: json-file
      options:
        max-size: '10m'
    read_only: true
    restart: on-failure:5
    cpu_shares: 128
    mem_limit: 268435456
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
