version: '2'

services:
  montdenis:
    image: vibioh/spring-web-bp
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: spring.${DOMAIN}'
      traefik.port: '8080'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    restart: on-failure:5
    cpu_shares: 128
    mem_limit: 268435456
#    security_opt:
#    - no-new-privileges

networks:
  default:
    external:
      name: traefik
