version: '2'

services:
  spring:
    image: vibioh/spring-web-bp
    command: -Xmx512M
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: spring.vibioh.fr, spring.l3miage.fr'
      traefik.port: '8080'
    logging:
      driver: json-file
      options:
        max-size: '50m'
    read_only: true
    restart: on-failure:5
    cpu_shares: 128
    mem_limit: 536870912
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
