apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spring-web-bp
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.59"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    skipCRDs: true
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: spring-web-bp
    image:
      name: vibioh/spring-web-bp
      tag: "202103221740" # {"$imagepolicy": "default:flux-spring-web-bp-api:tag"}
    ingress:
      enabled: true
      hosts:
      - spring.l3miage.fr
    port: 8080
    livenessProbePath: /actuator/health
    readinessProbePath: /actuator/health
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
