apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spring-boilerplate
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.1.2"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: spring-boilerplate
    image:
      name: rg.fr-par.scw.cloud/vibioh/spring-boilerplate
      tag: "202504072152" # {"$imagepolicy": "default:flux-spring-api:tag"}
    port: 8080
    prometheus:
      port: 8080
      path: /actuator/prometheus
    probes:
      initialDelaySeconds: 15
      readiness: /actuator/health
    autoscaling:
      enabled: false
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi
