apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spring-web-bp
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.84"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: spring-web-bp
    image:
      name: vibioh/spring-web-bp
      tag: "202203180749" # {"$imagepolicy": "default:flux-spring-web-bp-api:tag"}
    ingress:
      enabled: true
      hosts:
        - spring.l3miage.fr
    port: 8080
    prometheus:
      port: 8080
      path: /actuator/prometheus
    probes:
      initialDelaySeconds: 15
      readiness: /actuator/health
    autoscaling:
      enabled: false
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 128Mi
